### ISSUE TITLE
Telnet output is empty in random situations

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [3mdeb/meta-rte#28] opened 2022-08-22 08:11 UTC
**meta-rte version**

Every version up from 0.5.3

**Affected component(s) or functionality**

Telnet serial connection

**Brief summary**

An automated test environment is built based on RTE. When using a version of meta-rte newer than 0.5.3, the problems with the Telnet connection appear randomly: the tests fail because of the empty output - even though the DUT is powered on. 

**How reproducible**

Randomly. But if the bug occurs during the test suite preparation, it affects all test cases.

**How to reproduce**

The problem occurs randomly. Under the issue, I attach the logs from automatic tests.

**Expected behavior**

No problems with the opened Telnet connection

**Actual behavior**

Empty output in random situations.

**Screenshots**

**Additional context**

**Solutions you've tried**

1. Improving timeouts between turning on/off the device.

**Comment by sulewskiprzemyslaw** [comment] 2022-08-22 08:16
Under this link, the logs from tests are available: https://cloud.3mdeb.com/index.php/s/ZMFqHj5KaspaCwA.
The bug occurs for example in `Modem2-Detect-Debian` test suite. This test suite is located in `Hardware` test module.

**Comment by miczyg1** [comment] 2022-08-22 08:47
I believe we had enough of those timeouts between turning on/off the device. If this is still a problem, add the power LED connection to the DUT as it was intended right from the start of RTE existence. Check the power LED when doing any power transitions to verify the operation was successful.

**Comment by artur-rs** [comment] 2024-03-19 20:01
Closing, outdated

**Closed as completed by artur-rs** 2024-03-19 20:01 UTC
